# version: 2.3.{build}
configuration: Release
image: Visual Studio 2022
branches:
  only:
    - master
skip_tags: true

# dotnet_csproj:
#   patch: true
#   file: '**\*.csproj'
#   version: '{version}'
#   package_version: '{version}'
#   assembly_version: '{version}'
#   file_version: '{version}'
#   informational_version: '{version}'

build_script:
- cmd: >-
    echo %PATH%

    msbuild  ".\QuickLauncher\QuickLauncher.csproj" /t:Restore


    "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.com" ".\QuickLauncherInstaller\QuickLauncherInstaller.csproj" /clean "Release|x64"


    "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.com" ".\QuickLauncherInstaller\QuickLauncherInstaller.csproj" /build "Release|x64"

after_build:
- ps: .\after_build.ps1
- ps: ls
artifacts:

  # pushing a single file
  - path: QuickLauncherSetup-*.zip

deploy:
  release: 'QuickLauncher Release v'
  description: 'QuickLauncher'
  provider: GitHub
  auth_token:
    secure: s452Wm4c83j4hgPCWEqehMm2yJwdIXfx24S++aICPh/OfTmaJIBeLiH45Y3K00e+VtDRWYcnrj9vkM+Z1ZeYwUiwTF4C1Jt5nrftJFh6/a6/lFbVJjir5uwnqkhuVTD0 # your encrypted token from GitHub
  artifact: /QuickLauncherSetup-.+\.zip/ # upload all NuGet packages to release assets
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: false        # deploy on tag push only
