version: 2.2.{build}
configuration: Release
branches:
  only:
    - master
skip_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
- cmd: >-
    echo %PATH%

    msbuild  ".\QuickLauncher\QuickLauncher.csproj" /t:Restore


    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.com" ".\QuickLauncherSetup\QuickLauncherSetup.vdproj" /clean "Release"


    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.com" ".\QuickLauncherSetup\QuickLauncherSetup.vdproj" /build "Release"

after_build:
- ps: 7z a QuickLauncherSetup-${env:APPVEYOR_BUILD_VERSION}.zip QuickLauncherSetup\Release\*
- ps: ls
artifacts:

  # pushing a single file
  - path: QuickLauncherSetup-$(APPVEYOR_BUILD_VERSION).zip

deploy:
  release: QuickLauncher-v$(APPVEYOR_BUILD_VERSION)
  description: 'QuickLauncher'
  provider: GitHub
  auth_token:
    secure: dkuuUUu5SVpAdawNcb7E40lkJvcv+Fuqdc1zd/k0rkRWef3gfMHaOqgMD5VWJVmg # your encrypted token from GitHub
  artifact: QuickLauncherSetup-$(APPVEYOR_BUILD_VERSION).zip # upload all NuGet packages to release assets
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: false        # deploy on tag push only